# Generated by Django 5.2.9 on 2025-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('meet_intake', models.IntegerField(default=0)),
                ('fish_intake', models.IntegerField(default=0)),
                ('rice_intake', models.IntegerField(default=0)),
                ('vege_intake', models.IntegerField(default=0)),
                ('men_intake', models.IntegerField(default=0)),
                ('pan_intake', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('meet_goal', models.IntegerField(default=0)),
                ('fish_goal', models.IntegerField(default=0)),
                ('rice_goal', models.IntegerField(default=0)),
                ('vege_goal', models.IntegerField(default=0)),
                ('men_goal', models.IntegerField(default=0)),
                ('pan_goal', models.IntegerField(default=0)),
            ],
        ),
    ]
